### ISSUE TITLE
Does it support edns client subnet?

### ISSUE THREAD

**Issue by thb007** [Berkeley-Reject/Encrypted-DNS#5]
Does it support edns client subnet?
address ":" 1.0.0.1,114.114.114.114 "Do you support this? Fill in a dns ip. If the first dns is unstable, you can skip the second dns for analysis.

`"bootstrap_dns_address": {
    "address": "1.0.0.1,114.114.114.114",
    "port": 53
}`

**Comment by thb007** [comment]
Can chnroute still be carefully classified? China's chnroute is supported by default. If classified, China can be divided into provinces and cities. Then use different DNS for each province or city.

**Comment by Berkeley-Reject** [comment]
Currently it supports EDNS client subnet. Commit: 5afaaf53a8edeecfac610fd209aba478cede94d2
